version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chromadb
    volumes:
      - ./backend:/app
    networks:
      - cybersentinel-net

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - cybersentinel-net

  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    networks:
      - cybersentinel-net

  airflow:
    image: apache/airflow:3.1.8
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/tasks:/opt/airflow/tasks
      - airflow-logs:/opt/airflow/logs
    env_file:
      - .env
    depends_on:
      - airflow-db
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@cybersentinel.local &&
               airflow webserver & airflow scheduler"
    networks:
      - cybersentinel-net

volumes:
  chroma-data:
  airflow-db-data:
  airflow-logs:

networks:
  cybersentinel-net:
    driver: bridge
